vala-lang/valadoc-org

documentation/libgda-5.0/Gda-5.0.valadoc.metadata
documentation/libgda-5.0/libgda-5.0.catalog

from https://github.com/flobrosch/valadoc-org/pull/48

Added libgda-5.0 documentation directory

---

documentation/packages.xml

From https://github.com/flobrosch/valadoc-org/pull/48

Fix GXml-0.10 docs

---

src/generator.vala

This will make errors for doc building _not_ stop the whole build.

dont fail doc build if we cant build a single doc

---

README.md
data/search.php
data/tooltip.php
src/generator.vala

I swear I tested the search PR before submitting it, so I'm just going to blame quantium coding. This should fix some weird timeout issue causing PHP to crash when searching. Also a bunch of style changes because it's physically impossible for me not to include them in random PRs.

fix a couple of things post search PR

---

data/scripts/valadoc.js

js: don't muddle with image paths

---

documentation/packages.xml

added libcolumbus to packages.xml

extra-vapis: added libcolumbus

---

data/search.php
data/styles/main.css

This adds the search icons back

add icons back to search results

---

Makefile

clean up makefile

---

src/generator.vala

Use vapis from git repos over system vapis

---

data/index.php
data/search.php
data/templates/markup.htm.content.tpl
data/tooltip.php
src/doclet.vala

- also makes search and tooltips work locally again

Fix various URLs

---

src/generator.vala

This will make any error while generating docs be appended to the log instead of overwriting.
It will output something like this:
```bash
btkostner@Caprica:~/Projects/Web/valadoc-org$ cat LOG 
===== gvncpulse-1.0 =====
valadoc --target-glib 2.99 --driver "0.34" --importdir girs --doclet "." -o "tmp/gvncpulse-1.0" "girs/vala/vapi/gvncpulse-1.0.vapi" --vapidir "girs/vala/vapi" --girdir "girs/gir-1.0" --pkg gvnc-1.0 --importdir "girs/gir-1.0" --import GVncPulse-1.0 --metadatadir documentation/gvncpulse-1.0 --wiki documentation/gvncpulse-1.0/wiki
gvnc-1.0.vapi:95.26-95.43: error: The type name `GLib.SocketAddress' could not be found
Failed: 1 error(s), 0 warning(s)
===== gxml-0.10 =====
valadoc --target-glib 2.99 --driver "0.34" --importdir girs --doclet "." -o "tmp/gxml-0.10" …
```

append errors to log instead of overwrite

---

Makefile

This makes the deployment process go faster

Get only the latest commit on the vala extra git repositories

---

data/index.php
data/styles/main.css

rewrite nav using flexbox
kill the cheesy tag line

redo nav with flexbox

---

data/index.php
data/styles/main.css

builds on #67 
Adds fontawesome and vala community links to the navbar

Social links

---

data/styles/main.css

expand #content to fill view

---

.travis.yml

precise is going to be EOL soon too.

travis: Use trusty based build environment

---

src/generator.vala

The required commit in Valadoc https://git.gnome.org/browse/valadoc/commit/?id=c213d3c13fbc766395adbf63bd16c92089441220

Generate SVGs instead of PNGs

---

data/styles/main.css

* Remove vendor prefixed properties
* Adjust padding, don't hardcode height
* Vertically center logo image
* Remove unused text color property

clean up nav styles

---

data/scripts/valadoc.js

fix firefox loop bug

---

documentation/packages.xml

Include documentation for snapd-glib

---

documentation/packages.xml

untested, somebody please try to build this (add `libdazzle-1.0` to `make build-docs-mini` temporarily)
#121

add libdazzle docs

---

documentation/packages.xml

add libide

---

data/scripts/valadoc.js

Lower search delay

---

Makefile
data/scripts/valadoc.js
package.json

I'm on PHP 7.2, on Arch Linux. Let me know if this breaks things

Fix starting php server

---

data/scripts/valadoc.js

- hides tooltip when we click on a link
- if you focus the search box, hit down and then enter, it should open the page

Various fixes

---

data/index.php

I hear search engines like this kind of stuff

Add more meta and itemprop data

---

.travis.yml
Makefile
README.md
src/doclet.vala
src/generator.vala

Use vala 0.38.x

---

data/styles/main.css

This is not the tidiest fix, but it does fix it.

Fix #154: Footer is partially under the sidebar

---

documentation/packages.xml

Update home page link for QRencode

---

documentation/packages.xml

Add template-glib

---

documentation/packages.xml

cf. #186 
Depends on https://github.com/nemequ/vala-girs/pull/13

Add Guestfs-1.0

---

examples/gtk+-3.0/Gtk.Builder.ui
examples/gtk+-3.0/Gtk.Builder.vala
examples/gtk+-3.0/Gtk.Builder.xml
examples/gtk+-3.0/gtk+-3.0.valadoc.examples

There is no official documentation so here it is!

Add Vala GtkTemplate example

---

.gitignore
Makefile
README.md
data/scripts/valadoc.js

Fix devhelp downloads

---

data/index.php
data/opensearch.xml
package-lock.json

add opensearch

---

documentation/packages.xml

Add GMime 3.0 API docs

---

documentation/packages.xml

Add libhandy documentation

---

documentation/packages.xml

Enable GStreamer Editing Services

---

documentation/packages.xml

Remove libide

---

documentation/packages.xml

To merge once https://gitlab.gnome.org/GNOME/vala-extra-vapis/merge_requests/4 is merged

Add libcheck documentation

---

documentation/packages.xml

Add Graphene to documentation

---

documentation/packages.xml

Allows getting the documentation comments

Add Gir to libsvg-2.0

---

documentation/packages.xml

Provide GtkSourceView 4.0

---

documentation/packages.xml

Required by latest evolution-data-server

Add libical-glib library

---

src/generator.vala

Add link to the tutorial "[Learn Vala and Gtk+ from Scratch](https://www.youtube.com/playlist?list=PLriKzYyLb28mn2lS3c5yqMHgLREi7kR9-)" from Alessandro Castellani

Add link to Alessandro Castellani's vala tutorial

---

data/index.php

https://planet.vala-project.org/

Add Planet Vala link

---

data/styles/main.css

Fix extra search entry styles in webkit browsers

---

documentation/packages.xml

Add babl documentation

---

.github/workflows/publish.yml

Publish docs at 20:00 UTC

---

Dockerfile
documentation/packages.xml

Add goocanvas-2.0

---

src/generator.vala

Does what it says on the tin. Easier to debug in docker and therefor GitHub actions

log builds to stdout instead of LOG file

---

documentation/packages.xml
documentation/vte-2.90/Vte-2.90.valadoc.metadata
documentation/vte-2.90/vte-2.90.catalog

Remove Vte-2.90

---

documentation/packages.xml

gpseq: https://gitlab.com/kosmospredanie/gpseq
Closes #245

Add gpseq-1.0

---

Dockerfile

Don't use an intermediary container for Node.js but use Ubuntu 20.04 as a base to have the required dependencies

docker: Slim down the container creation size

---

.github/workflows/ci.yml
.github/workflows/publish.yml

This makes the checkout action faster and lighter

GitHub Actions: replace checkout@v1 with checkout@v2

---

.dockerignore
.github/workflows/ci.yml
.github/workflows/publish.yml
Dockerfile

Do ugly things because we always hit the limit of the CI

Docker: only do the final docker generation in docker, do the rest directly within the GitHub CI environment

---

documentation/clutter-gtk-0.10/clutter-gtk-0.10.catalog
documentation/packages.xml

They are both now long deprecated

Remove clutter-gtk-0.10 and clutter-gst-2.0

---

documentation/packages.xml

Add LibGrss library

---

documentation/packages.xml
src/generator.vala

Quite ugly, but not worse as the rest :-)

Handle multiple gir files per package

---

.editorconfig
Makefile
README.md
examples/gee-0.8/Gee.ArrayQueue.vala
examples/gee-0.8/Gee.Traversable.fold.vala
examples/gee-0.8/gee-0.8.valadoc.examples
examples/gtk+-3.0/Gtk.TreePath.vala

I have not been able to build valadoc-org yet, it complains:
```
warning: error: Package 'sdl2-net' not found
warning: error: Package 'sdl2-ttf' not found
warning: error: Package 'sdl2-mixer' not found
warning: error: Package 'sdl2-image' not found
warning: error: Package 'sdl2-gfx' not found
```
It seems to be unsure whether it's a warning or an error :) but it stops the build anyway.

Add an example for Gee

---

package-lock.json
package.json

npm outdated && npm update && npm audit fix

npm: Update dependencies

---

.github/workflows/ci.yml
.github/workflows/publish.yml
documentation/packages.xml

The CI basically ignores build failures :(

Fix github ci and publish

---

documentation/packages.xml
package-lock.json

Some updates and additions

---

documentation/packages.xml

Update http to https
Update developer.gnome to developer-old.gnome
Update GStreamer documentation

Update several documentation links

---

documentation/packages.xml

Add LibPortal

---

documentation/packages.xml

The version 0.0 has never been released, use 1.0 instead.

Switch libshumate to 1.0

---

data/index.php
src/generator.vala

Replace Planet Vala link with Vala 2022 wesbite link

---

data/index.php

Fix home icon typo

---

data/styles/main.css

Fix #389: Styles for tables in dark mode

Fix #389: Styles for tables in dark mode

---

Makefile
README.md

Also add documentation about it in the README

Add make target to install devhelp books

---

data/index.php

Just a small PR to close #399.

Removed the tagline from title

---

documentation/packages.xml

Deprecated and now mostly unused.

Remove libchamplain

---

data/scripts/valadoc.js

Add "/" keyboard shortcut to focus on search bar

---

data/search.php

Fixes #336 
- Search for " " shows backend warnings
- Searches with no results just result in a blank sidebar

Fix search edge cases
