vala-lang/valadoc-org

- Makefile
- Re-push of flobrosch/valadoc-org#63
- Works for any 0.x.x version.
- Builds to `valadoc-$version`
> Dynamically detect the ValaC version. 

- data/scripts/valadoc.js
When requesting from `search.php`, we pass a `curpkg` field which is taken from `clean_path()`
> Fix search from index.htm

- .gitignore
This means git doesn't think `documentation/granite` has untracked files
> ignore vapi-images in addition to gir-images

- data/search.php
- data/styles/main.css
It seems like the description here is pretty useless since you can't read the whole thing and some results don't even have one and it shows in the tooltip anyways.
If we remove it we can actually make the individual result items larger, which I think makes them easier to read and still save vertical space.
Should look like this:
> don't show descriptions in search results

- documentation/packages.xml
Some clean up:
- Add gxml-0.14
- Drop gstreamer-0.10 related packages and add gstreamer-1.0 ones
- Move dbus-glib-1.0 out of "core", gio-2.0 with GDbus is preferred
- Drop clutter-json-1.0
> Drop obsolete bindings and add missing ones

- data/index.php
- data/styles/main.css
- src/doclet.vala
- src/generator.vala
Getting rid of the xml header was done with the constructor argument: https://github.com/GNOME/vala/blob/bb5a612a7b22b14ac213f75bc5bf97f107a82636/libvaladoc/html/htmlmarkupwriter.vala#L28
> HTML5 improvements

- data/scripts/valadoc.js
This avoids the tooltip being under the cursor and blocking click actions.
> Move tooltip 2 pixels away from click area

- data/scripts/valadoc.js
Acording to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) there is a [bug with firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1101653) that makes the `const` value throw an error `missing = in const declaration`. Simple fix.
> fix firefox loop bug

- Makefile
- src/generator.vala
metadata_path is not an argument we can set, so it will always be null when we check to see if it's a file
fixes `(generator:27479): GLib-CRITICAL **: g_file_test: assertion 'filename != NULL' failed`
> Fix a critical error

- Makefile
As of commit https://github.com/php/php-src/commit/816758eda2bcdd69ba505fb6bbb79124a7bf2254 PHP looks for the router in the docroot. Older versions of PHP don't do this
> Fix router path for all php versions

- data/index.php
The link to http://stackoverflow.com/documentation/vala/ should be removed because it is dead.
Fixes elementary/website#1878
> Remove dead link

- data/index.php
- data/scripts/valadoc.js
Fixes #145: URL for external search (for valadoc DuckDuckGo !bang support)
- Parse URL [GET] Parameters
- Check for a "q" parameter
- Put it in the search box (UX)
- Trigger a search
> Fix #145: URL for external search (for valadoc DuckDuckGo !bang support)

- documentation/packages.xml
> Mark libvte-0.90 as deprecated

- .babelrc
- .gitignore
- gulpfile.babel.js
- package-lock.json
- package.json
- upgrade babel, gulp was really slow for me before this
- improve gulpfile indentation
- use the same env preset for postcss and babel
- `.babelrc`, i believe, is only used for reading `gulpfile.babel.js`
```
/tmp/valadoc-org(gulp*) » npm audit
=== npm audit security report ===                        
found 0 vulnerabilities
in 10860 scanned packages
```
> upgrade and improve babel and gulp config

- documentation/packages.xml
See https://github.com/Valadoc/valadoc-org/issues/189
> Change GLib-2.0 c-docs to stable URI

- Makefile
Since https://gitlab.gnome.org/GNOME/vala/commit/3d926c1288b3ec4fd692dd1de6b91fb6c2090183 the minimum GLib version should be even
> Use even GLib version to make latest Valac happy

- documentation/packages.xml
libgsignon-glib has been deprecated in favor of libsignon-glib
> Replace libgsignon-glib with libsignon-glib

- .travis.yml
- package-lock.json
- package.json
This fixes the one bad package in `npm audit`. Also uses `npm ci` to install the exact package version instead of automatically upgrading semver versions.
> update packages and npm commands

- documentation/packages.xml
libsocialweb itself is dead and folks-libsocialweb isn't available in any major distribution since ages
> Remove folks-libsocialweb

- documentation/packages.xml
Long deprecated and replaced by libsecret
> Remove GNOME keyring

- documentation/glib-2.0/glib-2.0.valadoc
Possibly fixes https://gitlab.gnome.org/GNOME/vala/issues/680
> GLib-2.0: be more specific in the documentation of float.MIN and double.MIN

- data/index.php
Since Google Plus is dead, there is no reason to link to it.
> Remove Google+ link

- .dockerignore
- Dockerfile
- Dockerfile-valadoc
- Makefile
- apache.conf
- docker-server.sh
This PR adds a `Dockerfile` that will produce a 4.4 GB (currently) docker image that contains all of the docs, the search backend, and a php server.
You can build and run it with:
```
docker build -t valadoc .
docker run --rm -it -p 3000:80 valadoc
```
This will start valadoc listenable on port 3000.
**NOTE** While the finished image is about 4.4 GB, building it will take more room.
> Docker images

- examples/glib-2.0/GLib.OptionContext.vala
Print option parsing errors on stderr instead of stdout.
Also, exit with status `1` to indicate failure to the caller.
> Print option parsing errors on stderr

- documentation/packages.xml
Because libecalendar-1.2 was an handcrafted vapi and libecal-2.0 is its future
Fixes #265
> Add libecal-2.0

- Dockerfile
- Makefile
It just slows down the dev process and usually has no effect. The README already tells users to run this.
> Remove `npm install` from serve-mini

- .github/workflows/publish.yml
Fix #295: Disable the publish to dockerhub action on forks of the repository.
> Fix #295: Only try to publish on the main repo

- Dockerfile
We are failing to build the container since bullseye is the new stable.
> Dockerfile: Use apache-buster

- .github/workflows/ci.yml
- .github/workflows/publish.yml
It has been incidently disabled in commit 98963ec4898c14ec4d57ce9a8bff0ff103496fb0#
> build: Do not disable devhelp for the standard build

- examples/glib-2.0/GLib.Test.run.vala
In the glib documentation, the example test suite returns the value of
g_test_run(). This seems to be the correct thing to do.
> examples/glib-2.0/GLib.Test.run.vala: use return value of Test.run

- data/index.php
Fixes #202 
Will allow users to add keywords for the Searchbox in Firefox to quickly search in Vala Doc. 
Done by Enclosing search box in <form> tag with action="/".
> Made Firefox recognize the searchbox

- documentation/packages.xml
The homepage listed on [the Valadoc page for`gudev`](https://valadoc.org/gudev-1.0/index.htm) is for a different (dead) project:
<http://gudev.sourceforge.net/>
Rather than the correct URL for `libgudev`:
<https://gitlab.gnome.org/GNOME/libgudev>
The links and description should be more in line with those on the corresponding PyGI page for `libgudev`:
<https://lazka.github.io/pgi-docs/GUdev-1.0/index.html>
These in turn appear to be copied from the GNOME Wiki page (which is little more than a bare set of links):
<https://wiki.gnome.org/Projects/libgudev>
I changed the "home" URL and also copied the description abstract from [the `libgudev` Gitlab README](https://gitlab.gnome.org/GNOME/libgudev/).
> Fix GUdev package listing

- documentation/packages.xml
Mark gcr-3 and gck-1 as deprecated as the new libraries are replacing them.
> Add gcr-4 and gck-2 libraries

- Makefile
- data/scripts/valadoc.js
- data/styles/main.css
A basic dark mode stylesheet, using the prefers-color-scheme media query. Fixes #271.
Object hierarchy graphs are still black on white. I'm not sure how to fix that yet.
Also, should the search box be light-on-dark as well? I tried it but I'm not sure if it looks right.
> Add dark mode using prefers-color-scheme

- documentation/packages.xml
- documentation/tracker-control-1.0/TrackerControl-1.0.valadoc.metadata
- documentation/tracker-miner-0.16/TrackerMiner-0.16.valadoc.metadata
- documentation/tracker-miner-1.0/Tracker-1.0.valadoc.metadata
All the tracker 2 libraries are now deprecated since a while.
> Replace tracker 2 with tracker 3

- data/index.php
If you scroll to the bottom of [vala.dev](https://vala.dev/), these are the links under "Community" and "Social".
To be fair the list of links in the Valadoc header and the list of links in the Vala.dev footer should probably be coordinated in a somewhat less ad-hoc manner, but this is probably an okay place to start.
Note: Font Awesome does not seem to have an icon for Matrix, so I used a generic hashtag icon, instead, on the basis that Matrix is conceptually similar to IRC—indeed the GNOME Matrix is bridged to the GNOME IRC—and the hashtag has historically been a symbol of IRC. A proper Matrix icon would probably be better, though.
> Add social links from vala.dev

- documentation/glib-2.0/glib-2.0.valadoc
The method does not necessarily read line terminating characters (for
example, at EOF).
The string returned does not contain line terminating characters.
> Improve documentation for FileStream.read_line

- .github/workflows/ci.yml
- Dockerfile
Node 18 (LTS/Hydrogen) went EOL in [October 2023](https://endoflife.date/nodejs) and loses its security support in April 2025.
Node 22 was promoted to an LTS release in October 2024, and we should probably move over.
> Move to a supported Node LTS

- src/generator.vala
- Updated links
- Removed `vala for java programmers link`.
> generator: Replace GNOME wiki links with vala.dev
